services:
  frontend:
    container_name: prn-assignment-frontend
    image: ghcr.io/tasuketesuvaroogu/prn-assignment-frontend:latest
    expose:
      - "5244"
    networks:
      - proxy
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL}
    restart: unless-stopped
  backend:
    container_name: prn-assignment-backend
    image: ghcr.io/tasuketesuvaroogu/prn-assignment-backend:latest
    platform: linux/arm64
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:6124
    expose:
      - "6124"
    networks:
      - proxy
    restart: unless-stopped      

networks:
  proxy:
     name: "nginx-pm"
     external: true